### ISSUE TITLE
Make JSON better

### ISSUE THREAD

**Issue by tfausak** [tfausak/octane#9]
https://github.com/tfausak/octane/issues/6#issuecomment-224913489

**Comment by tfausak** [comment]
I feel like we should come to some consensus about what the JSON should look like. @jjbott has already done a lot of work on the output format of his parser. I know @danielsamuels and @rustyfausak are using the output of Octane, so they may have some input about what they'd like to see. 

I have a rough sketch of what I'd like the JSON to look like. But first, a couple high-level thoughts:
- A lot of the information in the replay file is only there to make parsing the frames possible. For example, everything relating to the class property map. Should the JSON output include those things or not? I'm leaning toward not including it since you can't really do anything with it.
- Keys should probably be `"CamelCase"` instead of the more usual `"snake_case"` because that's what Rocket League uses for its own properties in the metadata. 
- Values should be as compact as possible. Octane does not do this well right now. For example, the ping should just be an integer, not some object that you have to destruct.

So here's what I think the JSON should look like:

``` js
{
  // Skip serializing the size and CRC values.

  // Combine both version numbers.
  "Version": "123.456",

  // Skip the label that's always "TAGame.Replay_Soccar_TA".

  // Call this "metadata" instead of "properties" to avoid confusion with
  // properties in the frame replications.
  "Metadata": {
    "Id": "123...",
    // ... and so on for the rest of the properties.
  },

  // Skip the second pair of size and CRC.

  // I think there's always one element in this list, so maybe we should
  // serialize that directly.
  "Levels": ["park_night_sfx"],

  // Only old replays have these, so maybe we should avoid serializing them.
  "Messages": {
    "123": // This is the frame number.
      {
        "Name": "...",
        "Content": "..."
      },
    // ... and so on.
  },

  // This could be called "TickMarks" instead.
  "Marks": {
    "123": // frame number
      "Team0Goal",
    // ...
  },

  // Skip packages, objects, names, classes, and the cache.

  // We could serialize the generated class property map, but what's the point?

  // The meat of the JSON.
  "Frames": [
    {
      "IsKeyFrame": true,
      "Number": 0, // This frame's position in the list.
      "Time": 0.123,
      "Delta": 0.123, // Is it necessary to include this?
      "Spawned": {
        "123": // actor ID
          {
            "Name": "Archetypes.Ball.Ball_Default",
            "ClassName": "TAGame.Ball_TA",
            "Position": [1, 2, 3], // could be `null`
            "Rotation": [1, 2, 3] // could be `null`
          },
        // ...
      },
      "Changed": {
        "123": // actor ID
          {
            "Engine.PlayerReplicationInfo:Ping": // property name
              6,
            // ...
          },
        // ...
      },
      "Destroyed": [
        123, // actor ID
        // ...
      ]
    },
    // ...
  ]
}
```

Thoughts?

**Comment by rustyfausak** [comment]
I wonder if including the type in the properties section is better:

`"Engine.PlayerReplicationInfo:Ping": { "type": "int", "value": 6 }, ..`

This would allow us to quickly build a majority of the properties without having to know that "Ping" is an int. Then again, a lot of the properties are custom data structures that we have to parse anyways.

What about stuff like `TAGame.RBActor_TA:ReplicatedRBState`? Will it be parsed before it gets put into JSON? Right now it looks like this:

```
"TAGame.RBActor_TA:ReplicatedRBState": {
    "tag": "PRigidBodyState",
    "contents": [
        true,
        [0,0,93],
        [-1.0000305,-1.0000305,-1.0000305],
        [0,0,81],
        [0,0,0]
    ]
},
```

Should it change to look something like this?

```
"TAGame.RBActor_TA:ReplicatedRBState": {
    "type": "RigidBodyState",
    "value": {
        "Position": [0,0,93],
        "Rotation": [-1.0000305,-1.0000305,-1.0000305],
        "LinearVelocity": [0,0,81],
        "AngularVelocity": [0,0,0]
    }
}
```

**Comment by tfausak** [comment]
You're right, I think we should include the types of the properties. Otherwise you'll need your own lookup table to make sense of it. I know of a few property types:
- Boolean: either `true` or `false`.
- Byte: just an integer. `123`
- Camera settings: an object with float values and these keys: `FOV`, `Height`, `Angle`, `Distance`, `Stiffness`, `SwivelSpeed`. `{ "FOV": 110, ...}`
- Demolition: not sure what to name them, but it's got: a boolean, and integer, another boolean, another integer, then two integral vectors.
- Enum: an integer. `123`
- Explosion: a boolean, an optional integer, and an integral vector. `{ "Flag": true, ... }`
- Flagged integer: a boolean and an integer. `{ "Flag": true, "Value": 123 }`
- Float: just a float. `12.34`
- Game mode: `1` for hockey, `2` for hoops. Maybe we could just encode a string instead of an integer.
- Integer: just an integer. `123`
- Online loadout: 3 integers, then an optional integer. No idea what they represent. 
- Loadout: integer version, body, decal, wheels, rocket trail, antenna, topper, some integer, and some optional integer. `{ "Body": "Octane", ... }`
- Location: an integral vector. `[1, 2, 3]`
- Music stinger: a flag, then two integers. Not entirely sure what they mean.
- Pickup: boolean, optional integer, another boolean.
- Private match settings: mutators string, "joinable by" integer, max players integer, game name string, password optional string, some flag. `{ "Name": "Hello", ... }`
- Q Word (whatever that is): 2 integers, but maybe they should be a single 64-bit integer.
  Edit: Duh, "Q Word" is short for "quad word", which is 4 words, which is 64 bits. 
- Relative rotation: float vector. `[1.2, 3.4, 5.6]`
- Reservation: player number, system ID, optional remote ID, local ID, optional player name, two random booleans. 
- Rigid body state: some flag, an integral vector, a float vector, two optional integral vectors. 
- String: a string. `"hello"`
- Team paint: team number, primary color int, accent color int, primary finish string, accent finish string.
- Unique ID: system ID, optional remote ID, local ID.
- Party leader: system ID, optional remote ID, local ID.

(Obviously I'm not close to actually understanding all these properties.) In general I think we should prefer descriptive objects over compact arrays. So for rigid body state, I'd prefer your second example to the first. I would also like to avoid magic numbers that require a lookup table. So instead of the loadout saying `{ "Body": 23 }`, it should say `{ "Body": "Octane" }`. 

Also I like the "type" and "value" names. (Except they should be capitalized.)

**Comment by danielsamuels** [comment]
Couple of thoughts from my perspective:
- Anything that makes the output smaller, or quicker to process is good.
- Any data that will never be used being removed is good.
- No need for frame number in the frame itself, you can get that from the item's index within the context of the network stream.
- I might be using the delta values in the near future, so I'd like to keep them.
- I'm not a fan of the multiple "properties" keys in the current output, it caused me to have to write `['properties']` an awful lot in my port from PyRope.
- I don't personally have any use for the property type in the output, as long as everything appears in a consistent manner, in the same order etc.
- I would say that mapping values manually in the parser will likely lead to problems in the future, as if the format changes, you'll need to release a new version. If you just return what comes out of the file, that will never be a problem - the consumers will just have to update their part.
- Consistency in general is useful, it means we can write a specification for parsers, provide example replays and people can check whether their parser matches what is expected.
- I personally prefer lower-case keys, but given that the values in the replay header contain upper-case characters, I'm happy to go with it.

In general, the quicker and smaller the data, the less money it costs me to process and store the data - so that's always appreciated..!

**Comment by jjbott** [comment]
I had different goals in mind when I did the JSON output, partially due to the use cases I had in mind. These are my personal opinions on the matter, feel free to ignore them. :)

One big difference is that I never wanted to add more info to the JSON that what was in the replay. Sure TeamColorId X is some #RRGGBB and HatProductId X is some kind of awesome hat, but my parser doesn't care. In my mind, that is static data that whatever is consuming the JSON may or may not care about, and I'll leave it to them. No reason to add that bloat if the consumer can have its own lookup table easily enough. Plus that means I don't have to decompile the source as often.

Some of that decision is also to reduce the file size of the JSON, which also why I don't include type names. Plus, if whatever is consuming the JSON doesn't know that property X is type Y, I can't imagine how adding type information will help it. The important info is the property name, and you either know how to handle it or you don't.

Beyond that sort of stuff, I also support 2 different versions of JSON. Each are useful in their own ways I think. My "raw" version of JSON outputs everything pretty much as-is. This is sometimes useful or debugging, or could possibly be used for more easily converting back to a binary replay file someday.

But I mainly use a "pretty" version that removes everything that no one cares about (well, based on a sample size of 1 :) ) and everything that can be deduced from other information. The JSON could possibly still be round-tripped back to a replay file, but you wouldn't have a good time, and it wouldn't match the original (although it'd hopefully be functionally equivalent). It also tries to make things easier for whatever would be consuming the JSON, hiding some RL implementation details.

A couple of examples regarding the "pretty" version... 

It removes all distinction between "new" and "updated" actors, calling both an "update". Any program following the stream already knows if the actor is new or existing, so the distinction just takes up space.

It kills all keyframe data, or more specifically, it omits all data that we already know if we've followed the stream from the beginning. I'm sure they're helpful in the real network stream (assuming they're actually in the true network stream, and not generated client side by RL) but otherwise, we don't need them. In theory they're useful during replay playback - when skipping forward or backwards you only have to resimulate from the most recent keyframe. But, my slow Javascript replay viewer can resimulate an entire replay from frame 0 pretty much instantly, so they're gone!

It doesn't bother with empty frames - either those that are truly empty, or those that are empty after removing data we already know. Along with that, anything that references frame ids had to reference times instead, since frame ids won't line up (and I don't put frame ids in the json because I don't care about them)

So yeah. Theres some stuff. That's a bunch of words. :)

**Comment by rustyfausak** [comment]
off topic - i did some work on getting a 3d view with rigid body orientations so i can do collision detection.. here's an enormous gif to showcase:

![game](https://cloud.githubusercontent.com/assets/1559512/15976584/57befca8-2f19-11e6-98b8-c2d3b8481d5c.gif)

**Comment by danielsamuels** [comment]
If you don't know about it already, there's a BallHit event which you might find useful for that. I'm making use of it for a new RLR feature I'm building.

**Comment by jjbott** [comment]
I should also say that I like some of the thoughts above. Looking at a random frame, my JSON currently looks like this: 

```
{
    "Time" : 216.261017,
    "DeletedActorIds" : [],
    "ActorUpdates" : [{
            "Id" : 192,
            "TAGame.RBActor_TA:ReplicatedRBState" : {
                "Sleeping" : false,
                "Position" : {
                    "X" : -395,
                    "Y" : -1722,
                    "Z" : 19
                },
                "Rotation" : {
                    "X" : 0.995056,
                    "Y" : -0.5683767,
                    "Z" : -0.9989013
                },
                "LinearVelocity" : {
                    "X" : 3004,
                    "Y" : 13779,
                    "Z" : 81
                },
                "AngularVelocity" : {
                    "X" : 0,
                    "Y" : 0,
                    "Z" : 0
                }
            }
        }, {
            "Id" : 191,
            "TAGame.RBActor_TA:ReplicatedRBState" : {
                "Sleeping" : false,
                "Position" : {
                    "X" : 204,
                    "Y" : -2341,
                    "Z" : 132
                },
                "Rotation" : {
                    "X" : 0.6653951,
                    "Y" : 0.834315,
                    "Z" : -0.9894101
                },
                "LinearVelocity" : {
                    "X" : -3106,
                    "Y" : 11727,
                    "Z" : -10567
                },
                "AngularVelocity" : {
                    "X" : 3148,
                    "Y" : -4174,
                    "Z" : 2945
                }
            }
        }, {
            "Id" : 175,
            "TAGame.Vehicle_TA:ReplicatedSteer" : 225
        }
    ]
}
```

I could definitely get behind shortening it down to something like this (converted by hand, so probably wrong):

```
"216.261017" : {
    "ActorUpdates" : {
        "192" : {
            "TAGame.RBActor_TA:ReplicatedRBState" : {
                "Sleeping" : false,
                "Position" : [-395, -1722, 19],
                "Rotation" : [0.995056, -0.5683767, -0.9989013],
                "LinearVelocity" : [3004, 13779, 81],
                "AngularVelocity" : [0, 0, 0]
        },
        "191" : {
            "TAGame.RBActor_TA:ReplicatedRBState" : {
                "Sleeping" : false,
                "Position" : [204, -2341, 132],
                "Rotation" : [0.6653951, 0.834315, -0.9894101],
                "LinearVelocity" : [-3106, 11727, -10567],
                "AngularVelocity" : [3148, -4174, 2945]
        },
        "175" : {
            "TAGame.Vehicle_TA:ReplicatedSteer" : 225
        }
    ]
}
```

The X/Y/Zs are just extra noise (and half wrong for rotations). Using the ids and times as a key saves space and makes logical sense I think.

I'm also toying with the idea of adding a string lookup to the JSON, more for my specific use case than for a general JSON standard. But thought I'd mention it. Like, the string "TAGame.RBActor_TA:ReplicatedRBState" will appear in the JSON about a trillion times. I can add it to a lookup (similar to the actual replay files and the list of objects) and use an arbitrary id instead. That wouldn't be readable at all, but it'd make the file size shrink a ton. After zipping, the file size may be a wash though.

**Comment by rustyfausak** [comment]
@danielsamuels are you talking about `TAGame.Ball_TA:HitTeamNum`? That only flips between the teams and won't show e.g. multiple consecutive hits

**Comment by danielsamuels** [comment]
Yeah, gzip makes the value of that sort of thing fairly moot.

**Comment by rustyfausak** [comment]
what's the point of making the JSON filesize small? isn't the use case piping the output of the replay parser into a replay analyzer? you can read a json using a stream so no need to put the whole thing in memory..

**Comment by danielsamuels** [comment]
@rustyfausak: I was, is that merely for controlling the ball's trail color then?

**Comment by jjbott** [comment]
I sort of figured. My dumb misconfigured web server refuses to gzip though, which is why I was thinking about it. :)

**Comment by rustyfausak** [comment]
@danielsamuels  yep, that's what i think

**Comment by jjbott** [comment]
My personal use case is loading stuff into http://bunkmonkey.com:97/Viewer2.htm . I don't want to have to send a 30MB json file to the client!  Gzip takes care of a lot of that, but every bit helps

**Comment by tfausak** [comment]
I don't think we should focus on reducing the file size of the JSON at the expense of making it easy to understand. Compression is amazing! 

```
octane> ls -lh *.json
-rw-r--r--  1 tfausak  wheel    66M Jun 10 11:44 replay-jjbott.json
-rw-r--r--  1 tfausak  wheel    27M Jun 10 11:19 replay-octane.json

octane> gzip --best *.json
octane> ls -lh *.gz
-rw-r--r--  1 tfausak  wheel   3.0M Jun 10 11:44 replay-jjbott.json.gz
-rw-r--r--  1 tfausak  wheel   1.1M Jun 10 11:19 replay-octane.json.gz

octane> for f in *.json; 7z a $f.7z $f; end
octane> ls -lh *.7z
-rw-r--r--  1 tfausak  wheel   3.1M Jun 10 15:02 replay-jjbott.json.7z
-rw-r--r--  1 tfausak  wheel   964K Jun 10 15:02 replay-octane.json.7z
```

**Comment by jjbott** [comment]
Oh gosh. I hope those two files aren't from the same replay, and the jjbott version isn't from my parser. Or I'll make a sad face since mine is so huge. :P

**Comment by rustyfausak** [comment]
@jjbott that replay viewer is awesome, you got interpolation looking nice - threejs doesn't look like it has collision checking but that seems like something you could figure out pretty easy.

**Comment by tfausak** [comment]
And to actually address some of the comments...

> No need for frame number in the frame itself

I like including it because it makes eyeballing things much easier. And you don't have to `enumerate` the list of frames just to get the number. And if you're looking at the JSON and see a mark associated with a frame, you can just search for that number to find it. 

> mapping values manually in the parser will likely lead to problems in the future, as if the format changes, you'll need to release a new version

I think that's fine. The replay format has to be backwards compatible, so the chances of Psyonix breaking the parser is pretty low. 

> we can write a specification for parsers, provide example replays and people can check whether their parser matches what is expected.

That's the dream! It would also make it easy to compare the relative performance of parsers. 

> I never wanted to add more info to the JSON that what was in the replay

I agree with you in that I don't want to add a bunch of crap to the JSON, but anyone wanting to make sense of the data will have to do the mapping. 

> whatever is consuming the JSON doesn't know that property X is type Y, I can't imagine how adding type information will help it

A consumer may not know what to do with `"Name": "TAGame.PRI_TA:bUsingBehindView"`, but it can more easily know how to interpret (i..e, parse) `"Type": "Boolean"`. 

> hiding some RL implementation details

I like the idea of removing all the extra replicated garbage on key frames, but that makes a "parser" more like a "simulator". I want to keep the parser lean and allow something else to make sense of the data it spits out. 

> I hope those two files aren't from the same replay

They aren't! But the jjbott version came from your webserver. The original file sizes don't matter much, which is what I was trying to prove.

**Comment by jjbott** [comment]
@rustyfausak Yeah that's sort of on my list. I'm over my head on 3d stuff (hell look at those "cars") so even though in theory I know where each car is, I.... don't know where each car is. :) 

Like, I want to emit some crummy particles when boost is on, but I don't know where the back of each car is, because i don't know what I'm doing. My attempts at turning the front tires to match the steering have been comical. I could figure it out, but I've also taken a break from it for the last month or so.
